"use client";

import ReactECharts from "echarts-for-react";
import { graphic } from "echarts";
import type { Sentiment, Summary, TopicPoint } from "../lib/api";
import { SENT_COLORS } from "./KpiCard";

const ORDER: readonly Sentiment[] = ["pos", "neu", "neg", "q"];
const AXIS = { axisLine:{lineStyle:{color:"rgba(255,255,255,0.16)"}}, axisLabel:{color:"#98A0BF",fontSize:10}, axisTick:{show:false}, splitLine:{show:false} };
const LIGHT_AXIS = { axisLine:{lineStyle:{color:"#CBD5E1"}}, axisLabel:{color:"#64748B",fontSize:10}, axisTick:{show:false}, splitLine:{show:false} };
const SPLIT = { lineStyle:{color:"rgba(255,255,255,0.055)"} };
const LIGHT_SPLIT = { lineStyle:{color:"#E2E8F0"} };
const TITLE = { textStyle:{color:"#F1F2FB",fontSize:14,fontWeight:800} };
const LIGHT_TITLE = { textStyle:{color:"#172033",fontSize:14,fontWeight:800} };
const LEGEND = { textStyle:{color:"#B9C0E2",fontSize:11,fontWeight:700}, icon:"roundRect", itemWidth:12, itemHeight:7, itemGap:16 };
const LIGHT_LEGEND = { textStyle:{color:"#475569",fontSize:11,fontWeight:700}, icon:"roundRect", itemWidth:12, itemHeight:7, itemGap:16 };
const lightMode=()=>typeof document!=="undefined"&&document.documentElement.dataset.theme==="light";
const axis=()=>lightMode()?LIGHT_AXIS:AXIS;
const split=()=>lightMode()?LIGHT_SPLIT:SPLIT;
const title=()=>lightMode()?LIGHT_TITLE:TITLE;
const legend=()=>lightMode()?LIGHT_LEGEND:LEGEND;
const muted=()=>lightMode()?"#64748B":"#65708F";
const chartText=()=>lightMode()?"#334155":"#C6CDEE";
function present(sum:Summary):Sentiment[]{return ORDER.filter((s)=>sum.sentiments.includes(s));}
function glow(color:string,blur=12){return {shadowColor:color,shadowBlur:blur,shadowOffsetY:2};}
function baseTooltip(borderColor:string){const light=typeof document!=="undefined"&&document.documentElement.dataset.theme==="light";return {backgroundColor:light?"#FFFFFF":"#141A2E",borderColor,textStyle:{color:light?"#172033":"#EEF0FF",fontSize:11},extraCssText:`border-radius:10px;box-shadow:${light?"0 10px 24px rgba(15,23,42,.12)":"0 14px 30px rgba(5,8,20,.35)"};`};}

export function TrendChart({sum}:{sum:Summary}){const topics=sum.per_topic.map(p=>p.topic_id);const series=present(sum).map(s=>({name:s,type:"line" as const,smooth:.48,showSymbol:true,symbol:"circle",symbolSize:7,connectNulls:true,lineStyle:{width:3,color:SENT_COLORS[s],...glow(SENT_COLORS[s],10)},itemStyle:{color:"#161D33",borderColor:SENT_COLORS[s],borderWidth:2,...glow(SENT_COLORS[s],9)},emphasis:{scale:1.55},areaStyle:{color:{type:"linear",x:0,y:0,x2:0,y2:1,colorStops:[{offset:0,color:`${SENT_COLORS[s]}24`},{offset:1,color:`${SENT_COLORS[s]}00`}] }},data:sum.per_topic.map((p:TopicPoint)=>p[s])}));return <ReactECharts notMerge lazyUpdate style={{height:320}} option={{backgroundColor:"transparent",title:{text:"Statistics — sentiment flow across topics",left:4,top:2,...(typeof document!=="undefined"&&document.documentElement.dataset.theme==="light"?LIGHT_TITLE:TITLE)},tooltip:{trigger:"axis",axisPointer:{type:"cross",lineStyle:{color:"rgba(167,139,250,0.35)"}},...baseTooltip("rgba(167,139,250,0.35)")},legend:{top:5,right:4,...(typeof document!=="undefined"&&document.documentElement.dataset.theme==="light"?LIGHT_LEGEND:LEGEND)},grid:{left:46,right:16,top:58,bottom:38},xAxis:{type:"category",boundaryGap:false,data:topics,name:"Topic ID",nameTextStyle:{color:muted()},...(typeof document!=="undefined"&&document.documentElement.dataset.theme==="light"?LIGHT_AXIS:AXIS)},yAxis:{type:"value",name:"count",nameTextStyle:{color:"#65708F"},...axis()},series}}/>}

export function RadarChart({sum}:{sum:Summary}){const cats=present(sum);const filt=cats.map(s=>+(sum.pct[s]??0).toFixed(1));const allTot=cats.reduce((a,s)=>a+(sum.overall_counts[s]??0),0);const all=cats.map(s=>allTot?+(((sum.overall_counts[s]??0)/allTot)*100).toFixed(1):0);return <ReactECharts notMerge style={{height:320}} option={{backgroundColor:"transparent",title:{text:"Performance — filtered vs overall (%)",left:4,top:2,...title()},tooltip:{...baseTooltip("rgba(45,212,191,0.35)")},legend:{bottom:2,...legend()},radar:{center:["50%","50%"],radius:"65%",indicator:cats.map(c=>({name:c.toUpperCase(),max:100})),axisName:{color:typeof document!=="undefined"&&document.documentElement.dataset.theme==="light"?"#475569":"#C6CDEE",fontSize:11,fontWeight:800},splitNumber:5,splitLine:{lineStyle:{color:["rgba(167,139,250,0.20)","rgba(167,139,250,0.13)","rgba(167,139,250,0.09)","rgba(167,139,250,0.07)","rgba(167,139,250,0.04)"]}},splitArea:{areaStyle:{color:["rgba(167,139,250,0.035)","rgba(20,26,48,0)"]}},axisLine:{lineStyle:{color:lightMode()?"#CBD5E1":"rgba(255,255,255,0.11)"}}},series:[{type:"radar",symbol:"circle",symbolSize:6,data:[{value:filt,name:"Filtered",lineStyle:{width:2.6,color:"#A78BFA",...glow("#A78BFA",11)},itemStyle:{color:"#A78BFA",borderColor:"#E7DEFF",borderWidth:1},areaStyle:{color:"rgba(167,139,250,0.24)"}},{value:all,name:"Overall",lineStyle:{width:2.6,color:"#2DD4BF",...glow("#2DD4BF",11),type:"dashed"},itemStyle:{color:"#2DD4BF",borderColor:"#D8FFFA",borderWidth:1},areaStyle:{color:"rgba(45,212,191,0.13)"}}]}]}}/>}

export function ActivityChart({sum}:{sum:Summary}){return <ReactECharts notMerge style={{height:285}} option={{backgroundColor:"transparent",title:{text:"Activity",left:4,top:2,...title()},tooltip:{trigger:"axis",...baseTooltip("rgba(96,165,250,0.35)")},grid:{left:44,right:16,top:52,bottom:36},xAxis:{type:"category",data:sum.per_topic.map(p=>String(p.topic_id)),name:"Topic ID",nameTextStyle:{color:"#65708F"},...AXIS},yAxis:{type:"value",name:"messages",nameTextStyle:{color:"#65708F"},...AXIS},series:[{type:"line",smooth:.48,showSymbol:true,symbol:"circle",symbolSize:6,data:sum.per_topic.map(p=>p.total),lineStyle:{width:3,color:"#60A5FA",...glow("#60A5FA")},itemStyle:{color:"#141A2E",borderColor:"#60A5FA",borderWidth:2,...glow("#60A5FA",9)},areaStyle:{color:{type:"linear",x:0,y:0,x2:0,y2:1,colorStops:[{offset:0,color:"rgba(96,165,250,0.34)"},{offset:.55,color:"rgba(96,165,250,0.11)"},{offset:1,color:"rgba(96,165,250,0.015)"}]}}}]}}/>}

export function TopicBars({sum}:{sum:Summary}){return <ReactECharts notMerge style={{height:285}} option={{backgroundColor:"transparent",title:{text:"Topic comparison",left:4,top:2,...title()},tooltip:{trigger:"axis",axisPointer:{type:"shadow"},...baseTooltip("rgba(167,139,250,0.35)")},legend:{top:5,right:4,...LEGEND},grid:{left:44,right:16,top:58,bottom:36},xAxis:{type:"category",data:sum.per_topic.map(p=>p.topic_id),name:"Topic ID",nameTextStyle:{color:"#65708F"},...AXIS},yAxis:{type:"value",...AXIS},series:present(sum).map(s=>({name:s,type:"bar" as const,barMaxWidth:21,barGap:"18%",itemStyle:{color:new graphic.LinearGradient(0,0,0,1,[{offset:0,color:SENT_COLORS[s]},{offset:1,color:`${SENT_COLORS[s]}77`}]),borderRadius:[6,6,2,2],...glow(SENT_COLORS[s],7)},emphasis:{itemStyle:{...glow(SENT_COLORS[s],17)}},data:sum.per_topic.map((p:TopicPoint)=>p[s])}))}}/>}

export function SentimentDonut({sum}:{sum:Summary}){const data=present(sum).map(s=>({name:s,value:sum.counts[s]??0,itemStyle:{color:SENT_COLORS[s],shadowBlur:16,shadowColor:SENT_COLORS[s]}}));return <ReactECharts notMerge style={{height:300}} option={{backgroundColor:"transparent",title:{text:"Distribution",left:4,top:2,...title()},tooltip:{trigger:"item",formatter:(p:any)=>`${p.name.toUpperCase()}<br/><b>${Number(p.value).toLocaleString()}</b> (${p.percent}%)`,...baseTooltip("rgba(167,139,250,0.35)")},legend:{bottom:2,...LEGEND},series:[{type:"pie",radius:["52%","76%"],center:["50%","52%"],avoidLabelOverlap:true,itemStyle:{borderColor:"#0B101B",borderWidth:3},label:{show:true,color:chartText(),fontSize:10,fontWeight:700,formatter:"{b}\n{d}%"},emphasis:{scale:true,scaleSize:6,label:{fontSize:12,fontWeight:900}},data}]}}/>}

export function StackedTopicChart({sum}:{sum:Summary}){const ps=present(sum);return <ReactECharts notMerge style={{height:300}} option={{backgroundColor:"transparent",title:{text:"Stacked",left:4,top:2,...title()},tooltip:{trigger:"axis",axisPointer:{type:"shadow"},...baseTooltip("rgba(45,212,191,0.35)")},legend:{top:5,right:4,...LEGEND},grid:{left:44,right:16,top:58,bottom:36},xAxis:{type:"category",data:sum.per_topic.map(p=>String(p.topic_id)),name:"Topic ID",nameTextStyle:{color:"#65708F"},...AXIS},yAxis:{type:"value",name:"messages",nameTextStyle:{color:"#65708F"},...AXIS},series:ps.map(s=>({name:s,type:"bar" as const,stack:"total",barMaxWidth:28,data:sum.per_topic.map(p=>p[s]),itemStyle:{color:SENT_COLORS[s],borderColor:"#0B101B",borderWidth:.5}}))}}/>}

export function SentimentHeatmap({sum}:{sum:Summary}){const ps=present(sum);const data:number[][]=[];sum.per_topic.forEach((p,ti)=>ps.forEach((s,si)=>data.push([ti,si,p[s]])));const max=Math.max(1,...data.map(d=>d[2]));return <ReactECharts notMerge style={{height:300}} option={{backgroundColor:"transparent",title:{text:"Heatmap",left:4,top:2,...title()},tooltip:{position:"top",formatter:(p:any)=>`Topic ${sum.per_topic[p.data[0]]?.topic_id}<br/><b>${ps[p.data[1]]?.toUpperCase()}</b>: ${p.data[2]}`,...baseTooltip("rgba(167,139,250,0.35)")},grid:{left:48,right:18,top:48,bottom:44},xAxis:{type:"category",data:sum.per_topic.map(p=>String(p.topic_id)),splitArea:{show:true,areaStyle:{color:["rgba(255,255,255,.015)"]}},...AXIS},yAxis:{type:"category",data:ps.map(s=>s.toUpperCase()),splitArea:{show:true,areaStyle:{color:["rgba(255,255,255,.015)"]}},...AXIS},visualMap:{min:0,max,calculable:false,orient:"horizontal",right:0,top:0,itemWidth:90,itemHeight:7,textStyle:{color:"#7F89A8",fontSize:9},inRange:{color:["#171D31","#51408A","#A78BFA"]}},series:[{type:"heatmap",data,emphasis:{itemStyle:{shadowBlur:14,shadowColor:"rgba(167,139,250,.65)"}},label:{show:true,color:"#EDEBFF",fontSize:9,fontWeight:800}}]}}/>}

export function SentimentGauge({sum}:{sum:Summary}){const pos=sum.pct.pos??0;return <ReactECharts notMerge style={{height:300}} option={{backgroundColor:"transparent",title:{text:"Gauge",left:4,top:2,...title()},tooltip:{formatter:`Positive: ${pos.toFixed(1)}%`,...baseTooltip("rgba(167,139,250,0.35)")},series:[{type:"gauge",center:["50%","58%"],radius:"72%",startAngle:210,endAngle:-30,min:0,max:100,splitNumber:5,progress:{show:true,width:16,roundCap:true,itemStyle:{color:SENT_COLORS.pos,shadowBlur:15,shadowColor:SENT_COLORS.pos}},axisLine:{lineStyle:{width:16,color:[[1,"rgba(255,255,255,.07)"]]}},axisTick:{show:false},splitLine:{length:7,lineStyle:{color:"rgba(255,255,255,.16)",width:1}},axisLabel:{color:"#77819E",fontSize:9,distance:10},pointer:{show:true,length:"60%",width:4,itemStyle:{color:typeof document!=="undefined"&&document.documentElement.dataset.theme==="light"?"#172033":"#F4F5FB"}},anchor:{show:true,size:9,itemStyle:{color:lightMode()?"#172033":"#F4F5FB"}},detail:{valueAnimation:true,formatter:"{value}%",color:"#F4F5FB",fontSize:28,fontWeight:900,offsetCenter:[0,"18%"]},data:[{value:+pos.toFixed(1)}]}]}}/>}
