"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityChart, RadarChart, SentimentDonut, SentimentGauge, SentimentHeatmap, StackedTopicChart, TopicBars, TrendChart } from "../components/Charts";
import { KpiCard, SENT_COLORS } from "../components/KpiCard";
import { fetchHealth, fetchMessages, fetchSummary, type Message, type Summary } from "../lib/api";

const sentimentLabels: Record<string,string>={pos:"Positive",neu:"Neutral",neg:"Negative",q:"Question"};
const sentimentOrder=["pos","neu","neg","q"] as const;
const PAGE_SIZE=20;
type ChartId="trend"|"radar"|"activity"|"topics"|"donut"|"stacked"|"heatmap"|"gauge";

export default function Home(){
  const [summary,setSummary]=useState<Summary|null>(null); const [messages,setMessages]=useState<Message[]>([]);
  const [health,setHealth]=useState("offline"); const [selectedSentiments,setSelectedSentiments]=useState<string[]>([]); const [selectedTopics,setSelectedTopics]=useState<number[]>([]);
  const [query,setQuery]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [sidebarOpen,setSidebarOpen]=useState(false);
  const [activeChart,setActiveChart]=useState<ChartId>("trend"); const [chartFullscreen,setChartFullscreen]=useState(false); const [page,setPage]=useState(1); const [autoRefresh,setAutoRefresh]=useState(false); const [theme,setTheme]=useState<"dark"|"light">("dark");

  const load=useCallback(async()=>{setLoading(true);setError("");const filters={sentiments:selectedSentiments,topics:selectedTopics,q:query};try{const [sum,rows]=await Promise.all([fetchSummary(filters),fetchMessages(filters,100)]);setSummary(sum);setMessages(rows.items);setPage(1)}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard data.")}finally{setLoading(false)}},[query,selectedSentiments,selectedTopics]);
  useEffect(()=>{fetchHealth().then(x=>setHealth(x.status||"online")).catch(()=>setHealth("offline"))},[]);
  useEffect(()=>{const saved=window.localStorage.getItem("wisesight-theme");if(saved==="light"||saved==="dark")setTheme(saved)},[]);
  useEffect(()=>{window.localStorage.setItem("wisesight-theme",theme);document.documentElement.dataset.theme=theme},[theme]);
  useEffect(()=>{const timer=setTimeout(load,350);return()=>clearTimeout(timer)},[load]);
  useEffect(()=>{if(!autoRefresh)return;const timer=setInterval(load,30000);return()=>clearInterval(timer)},[autoRefresh,load]);
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setChartFullscreen(false)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);

  const topics=useMemo(()=>summary?.topics??[],[summary]); const sum=summary; const sourceLabel=sum?sum.source:health;
  const activeFilters=selectedSentiments.length+selectedTopics.length+(query.trim()?1:0);
  const totalPages=Math.max(1,Math.ceil(messages.length/PAGE_SIZE)); const visibleMessages=messages.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  const toggle=(value:string|number,type:"sentiment"|"topic")=>{if(type==="sentiment")setSelectedSentiments(v=>v.includes(String(value))?v.filter(x=>x!==String(value)):[...v,String(value)]);else setSelectedTopics(v=>v.includes(Number(value))?v.filter(x=>x!==Number(value)):[...v,Number(value)])};
  const clearFilters=()=>{setSelectedSentiments([]);setSelectedTopics([]);setQuery("")};
  const exportCsv=()=>{if(!messages.length)return;const esc=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;const rows=["Raw text,Sentiment,Score,Topic,Keywords",...messages.map(m=>[esc(m.texts),esc(sentimentLabels[m.predicted_sentiment]??m.predicted_sentiment),esc(m.sentiment_score?.toFixed(3)??""),esc(m.topic_id??""),esc(m.topic_keywords??"")].join(","))];const blob=new Blob(["\uFEFF"+rows.join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`wisesight-analysis-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)};
  const chartTitle:Record<ChartId,string>={trend:"Sentiment flow",radar:"Performance",activity:"Activity",topics:"Topic comparison",donut:"Distribution",stacked:"Stacked",heatmap:"Heatmap",gauge:"Gauge"};
  const renderChart=(id:ChartId)=><>{id==="trend"&&sum&&<TrendChart sum={sum}/>} {id==="radar"&&sum&&<RadarChart sum={sum}/>} {id==="activity"&&sum&&<ActivityChart sum={sum}/>} {id==="topics"&&sum&&<TopicBars sum={sum}/>} {id==="donut"&&sum&&<SentimentDonut sum={sum}/>} {id==="stacked"&&sum&&<StackedTopicChart sum={sum}/>} {id==="heatmap"&&sum&&<SentimentHeatmap sum={sum}/>} {id==="gauge"&&sum&&<SentimentGauge sum={sum}/>}</>;

  return <main className={`min-h-screen ${theme==="light"?"theme-light":"theme-dark"} bg-[#0B0D12] text-[#E8EAF0]`}>
    <div className="pointer-events-none fixed inset-0 overflow-hidden"><div className="absolute inset-x-0 top-0 h-px bg-white/[.06]"/></div>
    <div className="relative mx-auto grid min-h-screen max-w-[1750px] grid-cols-1 lg:grid-cols-[250px_1fr]">
      {sidebarOpen&&<button aria-label="Close filters" onClick={()=>setSidebarOpen(false)} className="fixed inset-0 z-30 bg-black/50 backdrop-blur-sm lg:hidden"/>}
      <aside className={`fixed inset-y-0 left-0 z-40 w-[280px] border-r border-white/10 bg-[#0B101C]/95 p-5 shadow-2xl backdrop-blur-2xl transition-transform duration-300 lg:static lg:w-auto lg:translate-x-0 lg:shadow-none ${sidebarOpen?"translate-x-0":"-translate-x-full"}`}>
        <div className="mb-8 flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg border border-white/10 bg-white/[.05] text-sm font-black text-slate-200">W</div><div><div className="font-extrabold tracking-tight">Wisesight</div><div className="text-[10px] uppercase tracking-[.18em] text-slate-500">Sentiment Studio</div></div></div><button onClick={()=>setSidebarOpen(false)} className="rounded-lg p-2 text-slate-500 hover:bg-white/5 lg:hidden">×</button></div>
        <div className="mb-3 flex items-center justify-between"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Sentiment class</div>{selectedSentiments.length>0&&<span className="text-[10px] text-violet-300">{selectedSentiments.length} active</span>}</div>
        <div className="space-y-2">{sentimentOrder.map(s=><button key={s} onClick={()=>toggle(s,"sentiment")} className={`group flex w-full items-center gap-3 rounded-xl border px-3 py-2.5 text-left text-xs font-bold transition duration-200 ${selectedSentiments.includes(s)?"border-violet-400/30 bg-violet-400/10 text-white shadow-[inset_3px_0_0_#A78BFA]":"border-transparent text-slate-300 hover:translate-x-1 hover:bg-white/5"}`}><span className="h-2.5 w-2.5 rounded-full" style={{background:SENT_COLORS[s],boxShadow:selectedSentiments.includes(s)?`0 0 12px ${SENT_COLORS[s]}`:undefined}}/>{sentimentLabels[s]}<span className="ml-auto tabular-nums text-slate-500">{sum?.counts[s]??"—"}</span></button>)}</div>
        <div className="mt-8 mb-3 flex items-center justify-between"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Topic ID</div>{selectedTopics.length>0&&<span className="text-[10px] text-violet-300">{selectedTopics.length} active</span>}</div>
        <div className="flex max-h-[330px] flex-wrap gap-2 overflow-auto pr-1">{topics.map(t=><button key={t} onClick={()=>toggle(t,"topic")} className={`rounded-lg border px-2.5 py-1.5 text-[11px] font-bold transition duration-200 ${selectedTopics.includes(t)?"border-violet-400/50 bg-violet-400/15 text-violet-200 shadow-[0_0_15px_rgba(167,139,250,.08)]":"border-white/10 bg-white/[.025] text-slate-400 hover:border-white/20 hover:bg-white/5 hover:text-slate-200"}`}>{t}</button>)}</div>
        <div className="mt-8 rounded-2xl border border-white/10 bg-gradient-to-br from-violet-500/10 to-cyan-400/5 p-4"><div className="flex items-center justify-between"><span className="text-xs font-bold">Model status</span><span className={`h-2 w-2 rounded-full ${health==="offline"?"bg-rose-400":"bg-emerald-400 shadow-[0_0_12px_#34D399]"}`}/></div><div className="mt-2 text-[11px] text-slate-400">{health}</div><div className="mt-1 truncate text-[10px] text-slate-600">{sourceLabel}</div><button onClick={()=>setAutoRefresh(v=>!v)} className="mt-3 flex w-full items-center justify-between rounded-lg border border-white/5 bg-white/[.03] px-3 py-2 text-[10px] font-bold text-slate-400 hover:bg-white/[.06]"><span>Auto refresh</span><span className={`h-2 w-2 rounded-full ${autoRefresh?"bg-cyan-300 shadow-[0_0_10px_#67E8F9]":"bg-slate-700"}`}/></button></div>
      </aside>

      <section className="min-w-0">
        <header className="sticky top-0 z-20 border-b border-white/[.08] bg-[#070A12]/85 px-4 py-4 backdrop-blur-2xl md:px-8"><div className="flex items-center gap-3"><button onClick={()=>setSidebarOpen(true)} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/10 bg-white/[.04] text-slate-300 hover:bg-white/10 lg:hidden">☰</button><div className="min-w-0 flex-1"><div className="text-[10px] font-semibold uppercase tracking-[.18em] text-slate-500">Analytics</div><h1 className="mt-1 truncate text-xl font-extrabold tracking-tight">Wisesight Sentiment</h1></div><div className="hidden w-full max-w-md md:block"><div className="relative"><span className="pointer-events-none absolute left-3 top-2.5 text-slate-600">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search raw text…" className="h-10 w-full rounded-xl border border-white/10 bg-white/[.035] pl-9 pr-4 text-xs text-white outline-none transition focus:border-violet-400/40 focus:bg-white/[.055]"/></div></div><div className="hidden items-center gap-2 text-[11px] font-bold text-slate-400 sm:flex"><span className={`h-2 w-2 rounded-full ${health==="offline"?"bg-rose-400":"bg-emerald-400 shadow-[0_0_12px_#34D399]"}`}/>API {health}</div><button onClick={()=>setTheme(v=>v==="dark"?"light":"dark")} aria-label={`Switch to ${theme==="dark"?"light":"dark"} mode`} className="theme-toggle filter-chip border-white/10 bg-white/[.04] text-slate-300 hover:bg-white/10">{theme==="dark"?"☀ Light":"☾ Dark"}</button></div></header>

        <div className="space-y-6 p-4 md:p-8">
          <div className="animate-float-in"><div className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">Dashboard</div><div className="mt-1 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><h2 className="text-3xl font-black tracking-tight md:text-4xl">Sentiment overview</h2><p className="mt-1 text-sm text-slate-500">Wisesight Thai Sentiment &amp; Topic intelligence at a glance.</p></div><div className="flex flex-wrap items-center gap-2"><button onClick={clearFilters} disabled={!activeFilters} className="filter-chip border-white/10 bg-white/[.035] text-slate-400 hover:bg-white/[.07] disabled:cursor-not-allowed disabled:opacity-40">Reset filters</button><button onClick={exportCsv} disabled={!messages.length} className="filter-chip border-emerald-400/20 bg-emerald-400/10 text-emerald-200 hover:bg-emerald-400/15 disabled:opacity-40">↓ Export CSV</button><button onClick={load} className="filter-chip border-violet-400/20 bg-violet-400/10 text-violet-200 hover:bg-violet-400/15">↻ Refresh</button></div></div></div>
          <div className="flex flex-wrap items-center gap-2 rounded-2xl border border-white/[.08] bg-white/[.025] p-2.5 shadow-[0_12px_35px_rgba(0,0,0,.12)]"><span className="px-2 text-[10px] font-black uppercase tracking-[.16em] text-slate-600">Filters</span>{selectedSentiments.map(s=><button key={s} onClick={()=>toggle(s,"sentiment")} className="filter-chip border-violet-400/20 bg-violet-400/10 text-violet-200">{sentimentLabels[s]} <span>×</span></button>)}{selectedTopics.map(t=><button key={t} onClick={()=>toggle(t,"topic")} className="filter-chip border-cyan-400/20 bg-cyan-400/10 text-cyan-200">Topic {t} <span>×</span></button>)}{query.trim()&&<button onClick={()=>setQuery("")} className="filter-chip border-white/10 bg-white/5 text-slate-300">Search: {query.trim()} <span>×</span></button>}{!activeFilters&&<span className="px-2 text-[11px] text-slate-600">All data</span>}<span className="ml-auto px-2 text-[10px] font-bold text-slate-600">{loading?"Updating…":`${sum?.total.toLocaleString()??0} messages`}</span></div>
          {error&&<div className="rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-xs text-rose-200">{error}</div>}
          <div className="grid gap-4 md:grid-cols-3">{sum?<><KpiCard id="messages" title="Messages" sub="Filtered dataset" num={sum.total.toLocaleString()} pct={100} color="#60A5FA" icon="✦" foot={<>{sum.loaded.toLocaleString()} loaded · source {sum.source}</>}/><KpiCard id="positive" title="Positive" sub="Sentiment share" num={(sum.counts.pos??0).toLocaleString()} pct={sum.pct.pos??0} color={SENT_COLORS.pos} icon="+" foot={`${(sum.pct.pos??0).toFixed(1)}% of filtered messages`}/><KpiCard id="negative" title="Negative" sub="Sentiment share" num={(sum.counts.neg??0).toLocaleString()} pct={sum.pct.neg??0} color={SENT_COLORS.neg} icon="−" foot={`${(sum.pct.neg??0).toFixed(1)}% of filtered messages`}/></>: ["Messages","Positive","Negative"].map(x=><div key={x} className="lux-card h-[150px] animate-pulse"/>)}</div>

          {sum&&<>
            <div className="flex flex-wrap gap-2 rounded-xl border border-white/[.07] bg-[#0D121F]/70 p-1.5"><div className="px-3 py-2 text-[10px] font-black uppercase tracking-[.14em] text-slate-600">Explore</div>{([["trend","Sentiment flow"],["radar","Performance"],["activity","Activity"],["topics","Topic comparison"],["donut","Distribution"],["stacked","Stacked"],["heatmap","Heatmap"],["gauge","Gauge"]] as const).map(([id,label])=><button key={id} onClick={()=>setActiveChart(id)} className={`rounded-lg px-3 py-2 text-[11px] font-bold transition ${activeChart===id?"bg-white/10 text-white shadow-sm":"text-slate-500 hover:bg-white/5 hover:text-slate-300"}`}>{label}</button>)}<button onClick={()=>setChartFullscreen(true)} className="ml-auto rounded-lg px-3 py-2 text-[11px] font-bold text-slate-500 hover:bg-white/5 hover:text-white">⛶ Fullscreen</button></div>
            <div className="lux-card animate-float-in p-4 md:p-5">{renderChart(activeChart)}</div>

            <section className="lux-card overflow-hidden"><div className="border-b border-white/[.08] px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-extrabold">Raw Text <span className="text-slate-600">/</span> Analysis result</h3><p className="mt-1 text-xs text-slate-500">Live predictions returned by the dashboard API.</p></div><div className="flex items-center gap-2"><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[10px] font-bold text-slate-400">{messages.length} loaded</span><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[10px] font-bold text-slate-500">page {page}/{totalPages}</span></div></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-white/[.025] text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Raw text</th><th className="px-4 py-3">Sentiment</th><th className="px-4 py-3">Score</th><th className="px-4 py-3">Topic</th><th className="px-4 py-3">Keywords</th></tr></thead><tbody>{visibleMessages.map((m,i)=><tr key={`${m.texts}-${i}`} className="border-t border-white/5 transition hover:bg-violet-400/[.025]"><td className="whitespace-pre-wrap break-words px-5 py-3.5 align-top text-slate-300">{m.texts}</td><td className="px-4 py-3.5"><span className="rounded-full px-2.5 py-1 font-bold" style={{color:SENT_COLORS[m.predicted_sentiment]??"#94A3B8",background:`${SENT_COLORS[m.predicted_sentiment]??"#94A3B8"}15`}}>{sentimentLabels[m.predicted_sentiment]??m.predicted_sentiment}</span></td><td className="px-4 py-3.5 tabular-nums text-slate-400">{m.sentiment_score==null?"—":m.sentiment_score.toFixed(3)}</td><td className="px-4 py-3.5 text-slate-400">{m.topic_id??"—"}</td><td className="whitespace-pre-wrap break-words px-4 py-3.5 align-top text-slate-500">{m.topic_keywords??"—"}</td></tr>)}</tbody></table>{!loading&&messages.length===0&&<div className="p-10 text-center text-sm text-slate-500">No rows match the current filters.</div>}</div><div className="flex items-center justify-between border-t border-white/[.07] px-5 py-3"><span className="text-[10px] text-slate-600">Showing {(messages.length?((page-1)*PAGE_SIZE+1):0)}–{Math.min(page*PAGE_SIZE,messages.length)} of {messages.length}</span><div className="flex gap-2"><button disabled={page===1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="filter-chip border-white/10 bg-white/[.03] text-slate-400 disabled:opacity-30">← Prev</button><button disabled={page===totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))} className="filter-chip border-white/10 bg-white/[.03] text-slate-400 disabled:opacity-30">Next →</button></div></div></section>
            <section className="lux-card"><div className="px-5 py-4"><h3 className="font-extrabold">Topic keywords</h3><p className="mt-1 text-xs text-slate-500">Topic-level keyword summary.</p></div><div className="grid gap-2 border-t border-white/10 p-4 sm:grid-cols-2 lg:grid-cols-3">{sum.topic_keywords.map(t=><div key={t.topic_id} className="group rounded-xl border border-white/[.07] bg-white/[.025] p-3 transition hover:-translate-y-0.5 hover:border-violet-400/20"><div className="text-[10px] font-bold uppercase tracking-wider text-violet-300">Topic {t.topic_id}</div><div className="mt-1 text-xs leading-5 text-slate-400">{t.keywords}</div></div>)}</div></section>
          </>}
        </div>
      </section>
    </div>
    {chartFullscreen&&sum&&<div className="fixed inset-0 z-50 bg-[#05070D]/90 p-3 backdrop-blur-xl md:p-8"><div className="mx-auto flex h-full max-w-[1500px] flex-col rounded-3xl border border-white/10 bg-[#0B101B] shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-violet-300">Chart detail</div><h3 className="mt-1 text-lg font-extrabold">{chartTitle[activeChart]}</h3></div><button onClick={()=>setChartFullscreen(false)} className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-xs font-bold text-slate-300 hover:bg-white/10">Close ×</button></div><div className="min-h-0 flex-1 p-4 md:p-8">{renderChart(activeChart)}</div></div></div>}
  </main>
}
